# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres:alpine
    container_name: nba-postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/logs", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    volumes:
      # copy the CSV to create tables
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 3000:3000
