# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: nba-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ${PWD}/sql:/sql
    ports:
      - "5432:5432"
    

  adminer:
    image: adminer
    container_name: php-admin
    restart: always
    ports:
      - 8080:8080