# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres:alpine
    container_name: nba-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      # - ${PWD}/sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql


  adminer:
    image: adminer
    container_name: php-admin
    restart: always
    ports:
      - 8080:8080